### ISSUE TITLE
After updating to 2.0.4, Docker images failed to start.

### ISSUE THREAD

**Issue by YamatoRyou** [marcopeocchi/yt-dlp-web-ui#31]
`docker pull ghcr.io/marcopeocchi/yt-dlp-web-ui:latest`

```
2023-01-14T20:52:07.622611805Z Node.js v18.12.1
2023-01-14T20:52:10.546057358Z node:internal/modules/cjs/loader:998
2023-01-14T20:52:10.546513156Z   throw err;
2023-01-14T20:52:10.546546692Z   ^
2023-01-14T20:52:10.546569331Z
2023-01-14T20:52:10.546589092Z Error: Cannot find module '/usr/src/yt-dlp-webui/dist/main.js'
2023-01-14T20:52:10.546621895Z     at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
2023-01-14T20:52:10.546650453Z     at Module._load (node:internal/modules/cjs/loader:841:27)
2023-01-14T20:52:10.546675262Z     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
2023-01-14T20:52:10.546703896Z     at node:internal/main/run_main_module:23:47 {
2023-01-14T20:52:10.546727440Z   code: 'MODULE_NOT_FOUND',
2023-01-14T20:52:10.546749868Z   requireStack: []
2023-01-14T20:52:10.546769049Z }
```
